#include "gen-versioninfo.h"

#define FILEVER        GEN_VER_DIGITAL_VERSION
#define PRODUCTVER     GEN_VER_DIGITAL_VERSION
#define STRFILEVER     GEN_VER_VERSION_STRING
#define STRPRODUCTVER  GEN_VER_VERSION_STRING
